antora:
  extensions:
  - '@springio/antora-extensions/partial-build-extension'
  - ./lib/antora/extensions/inject-collector-config.js
  - ./lib/antora/extensions/version-fix.js
  - require: '@springio/antora-extensions/latest-version-extension'
  - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
  - '@antora/collector-extension'
  - ./lib/antora/extensions/fix-component-name-display.js
  - '@antora/atlas-extension'
  - require: '@springio/antora-extensions/tabs-migration-extension'
    # uncomment this option to save the migrated content to the worktree
    #save_result: true
    unwrap_example_block: always
  - require: '@springio/antora-extensions/publish-docsearch-config-extension'
    index_name: 'spring-security-docs'
    root_component_name: 'security'
  - require: '@springio/antora-extensions/root-component-extension'
    root_component_name: 'security'
site:
  title: Spring Security
  url: https://docs.spring.io/spring-security/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-security
    branches: [main, '5.{{6..9},{1..9}+({0..9})}.x', '6.+({0..9}).x']
    tags: ['5.{{6..9},{1..9}+({0..9})}.+({0..9})?(-RC+({0..9}))', '6.+({0..9}).+({0..9})?(-{RC,M}*)']
    start_path: docs
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.16/ui-bundle.zip
    snapshot: true
